// Terms & Conditions — the ONE source of the standard contract language, shared by the proposal PDF
// (printed last, lib/proposal-pdf.js) and the on-screen acceptance flow (the "Read the full Terms &
// Conditions" link in the signature modal), so what the customer signs matches the document exactly.
// Each clause = a short heading + body. Sensible industry defaults — have counsel review and adjust.
export const PROPOSAL_TERMS = [
  { h: "Acceptance & Scope", b: "This proposal defines the agreed scope of work, equipment, and pricing. Only the items listed are included; anything not expressly stated is excluded and requires a written change order. Signing the Acceptance, issuing a deposit, or authorizing work constitutes acceptance of these terms." },
  { h: "Pricing & Validity", b: "Prices are valid for 30 days from the issue date and may be revised after that period or if quantities, materials, or site conditions change. Prices exclude applicable sales tax unless stated." },
  { h: "Payment", b: "Payment is due per the Payment Terms schedule above. Past-due balances may accrue a service charge of 1.5% per month (or the maximum allowed by law), and work may be suspended until the account is current. Deposits are applied to the final balance." },
  { h: "Change Orders", b: "Changes to the scope, materials, device locations, or conditions discovered during the work are billed as additions at then-current rates and may affect the schedule. No change is binding until documented." },
  { h: "Site Access & Conditions", b: "The customer provides safe, timely access to all work areas, adequate 120V power, and a cleared work space. Delays, concealed conditions (e.g., inaccessible cable paths, hazardous materials, inadequate structure), or network/internet issues outside our control may incur additional charges." },
  { h: "Permits, Codes & Approvals", b: "Installation is performed to applicable codes and manufacturer specifications. Permit fees, inspections, HOA or landlord approvals, and any required low-voltage licensing fees are the customer's responsibility unless expressly included." },
  { h: "Equipment & Title", b: "Title to equipment passes to the customer upon receipt of full payment; risk of loss passes upon delivery or installation. We may substitute equipment of equal or greater capability when a specified item is unavailable." },
  { h: "Warranty", b: "Workmanship is warranted for 12 months from completion (or as stated for the project). Manufacturer warranties pass through to the customer. Warranty excludes damage from misuse, power surges or outages, acts of nature, tampering, relocation, or changes made by others." },
  { h: "Monitoring & Service", b: "Ongoing monitoring, maintenance, and service plans, where applicable, are governed by separate agreements and are not included in this proposal unless expressly stated." },
  { h: "Data, Recording & Privacy", b: "The customer is solely responsible for lawful use of cameras, recordings, and audio, including any notices or consent required by law, and for safeguarding access credentials and recorded footage." },
  { h: "Limitation of Liability", b: "Security and low-voltage systems reduce but do not eliminate risk, and IOT TECHS is not an insurer. To the maximum extent permitted by law, our total liability is limited to the amount paid for the work, and we are not liable for indirect, incidental, or consequential damages, including loss or theft of property." },
  { h: "Cancellation", b: "Cancellation after acceptance may incur charges for work already performed, non-returnable or special-order items, restocking fees, and a reasonable cancellation fee. Refund of any remaining deposit is net of these amounts." },
  { h: "Entire Agreement", b: "This proposal, together with the Payment Terms and Acceptance, is the entire agreement and supersedes prior discussions. It is governed by the laws of the state where the work is performed. If any provision is unenforceable, the remainder stays in effect." },
];
