// Default AI prompts for the site-survey tool. These are the fallbacks; an admin can
// override either one from the survey tool (stored in app_secrets as SURVEY_PROMPT_AERIAL
// / SURVEY_PROMPT_FLOORPLAN, read via secretValue). Reset = delete the override → this text.

// Enhance (aerial): light cleanup + minimal DECLUTTER. Remove loose movable junk so surfaces
// read clean, but keep every built/planted feature (house, pool, drives, trees, vehicles) and
// the house borders exactly as-is — no structural or drastic changes.
export const DEFAULT_AERIAL =
  "This is a real straight-down aerial photograph of a property. Return a photorealistic aerial photo — not an illustration, render, painting, 3D render, map graphic or cartoon. Do two light, realistic passes. CLEANUP: reduce noise and JPEG compression blocking, sharpen slightly, repair stitch seams and blurred patches, and even out harsh lighting while keeping natural daylight, real photographic grain and soft realistic shadows. If part of the frame is black, missing, or clearly a capture error, fill ONLY that area with plain matching ground texture (grass, pavement or roof) that naturally continues the surroundings — never fill a gap with water, a pool, or any new feature. DECLUTTER, minimally: remove small loose, movable clutter so every surface reads clean and uncluttered — scattered yard debris, hoses, tools, toys, garbage, bins and cans, bags, boxes, loose items and stray objects sitting on driveways, walkways, patios, decks and lawns (and, only if a pool is already present, around that pool), plus anything clearly obstructing the ground. Replace each removed item with the clean surface directly beneath it: dry clear pavement for driveways and paths, healthy even green for lawn, plain patio or deck for hard surfaces, and — only where an existing pool already is — clean even blue water. Make existing grass an even healthy green (remove small brown or bare patches) and make existing driveways, pavers and patios read clean and crisp; if — and only if — a pool already exists, make its water read clean and even too. KEEP EVERYTHING BUILT OR PLANTED, unchanged: the house and every building, roof, wall and garage; any existing pool's exact shape, size and position; driveways, walkways, patios, decks and fences; all trees, shrubs, bushes, hedges and garden beds; and parked vehicles — leave each exactly where it is, at the same size, shape and orientation. CRITICAL — no structural or drastic changes, and NEVER ADD A POOL: if there is no pool or water feature in the original photo, do not create, paint or imagine one anywhere — a pool may only be cleaned when it already exists, never added. Likewise never add, move, resize, reshape or invent any structure, pool, pond, fountain, building, addition, deck, shed, driveway, fence, tree or vehicle. Prioritize keeping the house footprint and every structure and property border exactly as given. Keep the framing and every edge exactly as given — no crop, zoom, pan, tilt, rotation or keystone. Only loose surface clutter may be removed; everything built or planted stays, and nothing new is ever added.";

// Floor-plan Generate: turn the labeled sketch into a clean 2D architectural plan.
// The route appends the room labels to the end at call time.
export const DEFAULT_FLOORPLAN =
  "Turn this labeled sketch into a clean, professional architectural floor plan drawing, top-down, black lines on a white background. The faint photo and coloured lines show the layout: convert them into crisp walls, rooms and openings. Keep every room, wall, door and boundary in the same position, proportion and orientation as drawn. Honour the text labels by printing each as a clean name in its space. Draw doors as gaps or swing arcs and walls as double lines. Keep it a precise 2D architectural floor plan — not a 3D render, not perspective, not a photograph. Thin uniform line weight, simple drafting style.";

// Site Intelligence (Phase 7): ANALYZE the real aerial — never regenerate it. The model returns
// structured polygons (as image fractions) that become SUGGESTIONS the technician reviews; nothing
// is applied automatically. The route validates every vertex and zone type before it is stored.
export const DEFAULT_SITE_INTEL =
  "You are analyzing a REAL straight-down aerial photograph of a property to help a security technician understand the site. This is an ANALYSIS task ONLY: you look at the existing photo and report what is there. Do NOT regenerate, redraw, repaint, enhance, describe changing, or hallucinate any pixels — the image is fixed evidence, not something to modify. " +
  "COORDINATES: a measurement grid and site-coordinate overlay accompany this image; those grid/site coordinates are the AUTHORITATIVE spatial reference — defer to them for location and scale, do not second-guess them. Output every polygon vertex as a FRACTION of the image dimensions: x in [0,1] from the left edge, y in [0,1] from the top edge. Never output pixels. " +
  "TRUSTED STRUCTURE: if a technician-confirmed Structure (the building footprint / primary structure) is provided in the context, TRUST it as given — do not rediscover, move, reshape, or replace it; analyze the site AROUND it. " +
  "SITE BOUNDARY: any site/property boundary you return is an APPROXIMATE working outline to orient the technician. It is NOT a surveyed, legal, recorded, or parcel boundary and must NEVER be described or labeled as one. State it only as an approximate boundary and give it a confidence. " +
  "ZONES: identify functional exterior zones using ONLY these supported types — street, sidewalk, curb, driveway, parking, front_yard, rear_yard, side_yard, alley, loading, entrance, pedestrian_approach, vehicle_approach. Do not invent other types. Return a polygon (image fractions) and a 0..1 confidence for each. " +
  "ORIENTATION: where the evidence supports it, report which side of the image is the front, rear, left and right of the property (short labels), with a confidence. " +
  "DO NOT INVENT: only report features you can actually see. If you are unsure a feature exists, omit it rather than guessing. When uncertain, lower the confidence; never fabricate a zone, boundary, or orientation to fill the schema. " +
  "Return ONLY a JSON object, no markdown fences, no prose, of the shape: " +
  "{ \"siteBoundary\": { \"polygon\": [[x,y],...], \"confidence\": 0..1 } | null, " +
  "\"orientation\": { \"front\": string|null, \"rear\": string|null, \"left\": string|null, \"right\": string|null, \"confidence\": 0..1 } | null, " +
  "\"zones\": [ { \"type\": one of the supported types, \"polygon\": [[x,y],...], \"confidence\": 0..1 } ] }. " +
  "Every polygon must have at least 3 vertices. Confidence is always a number between 0 and 1.";

// Keys under which admin overrides are stored in the vault (app_secrets).
export const PROMPT_KEYS = { aerial: "SURVEY_PROMPT_AERIAL", floorplan: "SURVEY_PROMPT_FLOORPLAN", SITE_INTEL: "SURVEY_PROMPT_SITE_INTEL" };
