// Default AI prompts for the site-survey tool. These are the fallbacks; an admin can
// override either one from the survey tool (stored in app_secrets as SURVEY_PROMPT_AERIAL
// / SURVEY_PROMPT_FLOORPLAN, read via secretValue). Reset = delete the override → this text.

// Enhance (aerial): light cleanup + minimal DECLUTTER. Remove loose movable junk so surfaces
// read clean, but keep every built/planted feature (house, pool, drives, trees, vehicles) and
// the house borders exactly as-is — no structural or drastic changes.
export const DEFAULT_AERIAL =
  "This is a real straight-down aerial photograph of a property. Return a photorealistic aerial photo — not an illustration, render, painting, 3D render, map graphic or cartoon. Do two light, realistic passes. CLEANUP: reduce noise and JPEG compression blocking, sharpen slightly, repair stitch seams and blurred patches, and even out harsh lighting while keeping natural daylight, real photographic grain and soft realistic shadows. If part of the frame is black, missing, or clearly a capture error, fill ONLY that area with plain matching ground texture (grass, pavement or roof) that naturally continues the surroundings. DECLUTTER, minimally: remove small loose, movable clutter so every surface reads clean and uncluttered — scattered yard debris, hoses, tools, toys, garbage, bins and cans, bags, boxes, loose items and stray objects sitting on driveways, walkways, patios, decks, lawns and around the pool, plus anything clearly obstructing the ground. Replace each removed item with the clean surface directly beneath it: dry clear pavement for driveways and paths, clean even blue water for the pool, healthy even green for lawn, plain patio or deck for hard surfaces. Make existing grass an even healthy green (remove small brown or bare patches) and make existing driveways, pavers, patios and the pool read clean and crisp. KEEP EVERYTHING BUILT OR PLANTED, unchanged: the house and every building, roof, wall and garage; the pool's exact shape, size and position; driveways, walkways, patios, decks and fences; all trees, shrubs, bushes, hedges and garden beds; and parked vehicles — leave each exactly where it is, at the same size, shape and orientation. CRITICAL — no structural or drastic changes: never add, move, resize, reshape or invent any structure, pool, building, addition, deck, shed, driveway, fence, tree or vehicle. Prioritize keeping the house footprint and every structure and property border exactly as given. Keep the framing and every edge exactly as given — no crop, zoom, pan, tilt, rotation or keystone. Only loose surface clutter may be removed; everything built or planted stays.";

// Floor-plan Generate: turn the labeled sketch into a clean 2D architectural plan.
// The route appends the room labels to the end at call time.
export const DEFAULT_FLOORPLAN =
  "Turn this labeled sketch into a clean, professional architectural floor plan drawing, top-down, black lines on a white background. The faint photo and coloured lines show the layout: convert them into crisp walls, rooms and openings. Keep every room, wall, door and boundary in the same position, proportion and orientation as drawn. Honour the text labels by printing each as a clean name in its space. Draw doors as gaps or swing arcs and walls as double lines. Keep it a precise 2D architectural floor plan — not a 3D render, not perspective, not a photograph. Thin uniform line weight, simple drafting style.";

// Keys under which admin overrides are stored in the vault (app_secrets).
export const PROMPT_KEYS = { aerial: "SURVEY_PROMPT_AERIAL", floorplan: "SURVEY_PROMPT_FLOORPLAN" };
